### ISSUE TITLE
Allow passing the data via URL (either by query string or dynamic segment)

### ISSUE THREAD

**Issue by twokul** [rwjblue/ember-live-api#3]

**Comment by rwjblue** [comment]
The default location to load the API data from right now is: /api/api.json, but it can now be configured via a URL param.  

The following is an example (using the tests version of the API docs):

http://rwjblue-ember-live-api.s3-website-us-east-1.amazonaws.com/?dataUrl=/tests/support/api.json

The URL looks a little odd when you have a class selected:

http://rwjblue-ember-live-api.s3-website-us-east-1.amazonaws.com/?dataUrl=/tests/support/api.json#/classes/Ember.Application/all

But most of the time you will be using the default API docs (release channel) so that shouldn't be a huge issue.
