### ISSUE TITLE
Figure out rendering speed issues (takes 1/2 second to switch from index view to method view, why?)

### ISSUE THREAD

**Issue by twokul** [rwjblue/ember-live-api#5]

**Comment by rwjblue** [comment]
My initial thoughts are that the markdown processing & highlighting are slowing down the display of these routes.  One possible solution might be to delay rendering some of the class items (similar to https://github.com/emberjs/list-view).

**Comment by rwjblue** [comment]
The speed seems much better since the _promise_ refactoring.  The longest time I can find between switching items is around 150ms (and that is for Ember.Application which has a lot of methods).

Play around with an S3 static site [here](http://rwjblue-ember-live-api.s3-website-us-east-1.amazonaws.com/).

I definitely think we could get better, but it is probably good enough IMHO. What do you guys think?

**Comment by rwjblue** [comment]
I think this is probably good enough for now, we can revisit later if we need/want to.

**Comment by stefanpenner** [comment]
which refactoring?

**Comment by rwjblue** [comment]
@stefanpenner - Refactoring this app (not RSVP or Ember), to use promises properly (my initial implementation was crazy).

**Comment by rwjblue** [comment]
I believe this was the culmination: https://github.com/rjackson/ember-live-api/commit/5407790b2c8c2955136ae38787d20a704e752b01.
